language: emacs-lisp
sudo: no

env:
 - EVM_EMACS=emacs-26.1-travis

# Install EVM, version EVM_EMACS
install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > travis.sh && source ./travis.sh

# run the tests
script:
  - ./run-travis-ci.sh
